"""Artifact publishing: uploads results to HuggingFace Hub."""

from __future__ import annotations

import logging
import subprocess
from pathlib import Path

logger = logging.getLogger(__name__)


class ArtifactPublisher:
    """Publishes experiment artifacts to HuggingFace Hub.

    Uploads: PDF paper, code diffs, checkpoints, logs.
    Tags with git commit hash.
    """

    def __init__(
        self,
        repo_id: str,
        *,
        token: str | None = None,
    ) -> None:
        self.repo_id = repo_id
        self.token = token

    def publish(
        self,
        artifacts: dict[str, Path],
        commit_message: str = "Ratiocinator experiment results",
        tags: dict[str, str] | None = None,
    ) -> str:
        """Upload artifacts to HuggingFace Hub.

        Args:
            artifacts: Mapping of filename → local path.
            commit_message: Commit message for the upload.
            tags: Optional metadata tags (e.g., git_hash, experiment_id).

        Returns:
            The URL of the uploaded commit.
        """
        try:
            from huggingface_hub import HfApi
        except ImportError as e:
            raise ImportError(
                "huggingface_hub is required for artifact publishing. "
                "Install with: pip install huggingface_hub"
            ) from e

        api = HfApi(token=self.token)

        # Ensure repo exists
        api.create_repo(self.repo_id, exist_ok=True, repo_type="dataset")

        # Upload each artifact
        uploaded = []
        for filename, local_path in artifacts.items():
            if not local_path.exists():
                logger.warning("Artifact not found: %s", local_path)
                continue
            api.upload_file(
                path_or_fileobj=str(local_path),
                path_in_repo=filename,
                repo_id=self.repo_id,
                repo_type="dataset",
                commit_message=f"{commit_message}: {filename}",
            )
            uploaded.append(filename)
            logger.info("Uploaded %s → %s/%s", local_path, self.repo_id, filename)

        # Add metadata card
        if tags:
            card_content = self._build_card(tags, uploaded)
            api.upload_file(
                path_or_fileobj=card_content.encode(),
                path_in_repo="README.md",
                repo_id=self.repo_id,
                repo_type="dataset",
                commit_message=f"{commit_message}: metadata",
            )

        url = f"https://huggingface.co/datasets/{self.repo_id}"
        logger.info("Published %d artifacts to %s", len(uploaded), url)
        return url

    def _build_card(self, tags: dict[str, str], files: list[str]) -> str:
        """Build a dataset card with experiment metadata."""
        lines = [
            "---",
            "tags:",
            "  - ratiocinator",
            "  - automated-research",
        ]
        for key, value in tags.items():
            lines.append(f"  - {key}:{value}")
        lines.extend([
            "---",
            "",
            "# Ratiocinator Experiment Results",
            "",
            "Automated experiment results generated by Ratiocinator.",
            "",
            "## Metadata",
            "",
        ])
        for key, value in tags.items():
            lines.append(f"- **{key}**: `{value}`")
        lines.extend([
            "",
            "## Files",
            "",
        ])
        for f in files:
            lines.append(f"- `{f}`")
        return "\n".join(lines) + "\n"


def get_git_hash(repo_path: Path | None = None) -> str:
    """Get the current git commit hash."""
    cmd = ["git", "rev-parse", "HEAD"]
    try:
        result = subprocess.run(
            cmd,
            cwd=repo_path,
            capture_output=True,
            text=True,
            check=True,
        )
        return result.stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"
